#!/bin/sh -e

arg="${1:-.}"

if [ -d "$arg" ]; then
    cd "$arg"
    echo hash zoxide &>/dev/null && zoxide add .
    exec "$VEDITOR" . >/tmp/editor-log 2>&1 &
elif [ -f "$arg" ]; then
    exec "$VEDITOR" "$arg" >/tmp/editor-log 2>&1 &
else
    echo "No such file or directory: $arg"
    exit 1
fi
